### PR TITLE
search for posts in sub-directories

### PR DESCRIPTION
**Pull request by junovell**
Just makes the program look for posts in sub-directories created under the content path which is how jekyll works.

This will help with organizing posts visually.

example (this doesn't wok on master):
```
Content/blog/
   - graphics/
       - how-to-do-physics-based-rendering.md
   - web/
       - starting-with-blazorstatic.md
   - linux/
       - setting-up-arch.md
```

One more thing that can be changed is the value of `FileNameNoExtension`, instead of just the file's name it can also contain it's relative path to the content folder (eg. `linux/setting-up-arch` instead of just `setting-up-arch`).
Or the user can choose to add a field to their FrontMatter class to differentiate between posts.

### CODE REVIEW

**Comment by tesar-tech** [comment]
Nice, thanks for the addition. 

- I made the `FileNameNoExtension` into `relative path of file with no extension to content path` by function. Now the posts are located in respective folders (`/blog/subfolder/post-in-subfolder` has its origin in `Content/Blob/subfolder/post-in-subfolder.md`) 
- I changed the BlogPage to accept multiple segments in parameter (using wildcard).
- Test post is there.

Does that suit your needs now?

How should we name the `FileNameNoExtension`, it is basically url for the future post...

**Comment by junovell** [comment]
I think it can be renamed to just `name`, `path` or `url` (like jekyll).

Also will this work with the media folder? i didn't use any media in my project so far so i didn't test if i can have subddirs there or not.

**Comment by tesar-tech** [comment]
`Url` it is.

The media folder works, it just copies the whole folder.

Do you wish to add yourself as a co-author to the `blog/subfolder/post-in-subfolder` post?

**Comment by junovell** [comment]
no that's fine, thanks for the help with this.

**Pull request merged**
